### ISSUE TITLE
[Focal devel] tiny scaling due to system changes, regarding auto-scaling

### ISSUE THREAD

**Issue by luksus42** [nitanmarcel/cinny-click-packaging#23]
The default scaling on Ubuntu Touch devices (phones) is too small and the app appears in desktop-mode, which makes it hard to use on a mobile-phone-screen. 

**To Reproduce**
1. Ubuntu Touch version must be the devel-channel of 20.04 (Focal Fossa)
2. Just start the app

**Expected behavior**
The app should start in mobile-device mode (not desktop-mode) and proper scaling.

**Screenshots**
![grafik](https://github.com/nitanmarcel/cinny-click-packaging/assets/6659488/1c7d68e3-a3ec-453d-ba80-8589666f871f)

**Additional context**
That issue is caused by changes of https://gitlab.com/groups/ubports/development/core/-/epics/39.
fyi @sunweaver

**Comment by nitanmarcel** [comment]
This would fix it? `QT_AUTO_SCREEN_SCALE_FACTOR` ?

**Comment by luksus42** [comment]
To be honest, I don't know.
Waiting for @sunweaver to clarify this.

**Comment by nitanmarcel** [comment]
Update on this. We'll have to wait, for OTA2, this change will either get reverted. From my understanding of the issue this is a regression in the PR mentioned.

Read from https://t.me/ubports_devel/73290

**Comment by nitanmarcel** [comment]
@luksus42 are you on the latest devel to test if it was already fixed? Someone in the devel group said that `AA_EnableHighDpiScaling` should work now

**Comment by lduboeuf** [comment]
should be good now ? No issues for me

**Comment by luksus42** [comment]
> @luksus42 are you on the latest devel to test if it was already fixed? Someone in the devel group said that `AA_EnableHighDpiScaling` should work now

Its working and scaling is correct again. But as I understand the change was just reverted and it may be a topic again in future releases of UT.

**Comment by nitanmarcel** [comment]
Awesome thanks.

**Comment by sunweaver** [comment]
> > @luksus42 are you on the latest devel to test if it was already fixed? Someone in the devel group said that `AA_EnableHighDpiScaling` should work now
> 
> Its working and scaling is correct again. But as I understand the change was just reverted and it may be a topic again in future releases of UT.

The change is not reverted, really, we more or less went on a side-effects Germany that shows what happens when session-wide setting QT_AUTO_SCREEN_SCALE_FACTOR to 1 or 0 instead of not setting it, at all.

It seems that either value for QT_AUTO_SCREEN_SCALE_FACTOR has quite an impact in that sense, that the env var setting gets enforced even if configured otherwise on a per application level.

See https://gitlab.com/ubports/development/core/ubuntu-touch-session/-/merge_requests/43

Long term solution shall be to use Qt auto-scaling, but we still need to investigate on qtwebengine and some other apps why the broke with qt auto-scaling enforced.
